"""
Query generation.

Turns a single subject string ("Google Wiz acquisition") into a broad set
of search queries covering announcement, financial, advisory, regulatory
and publisher-specific angles — without hard-coding the subject itself.

Phase 1 ships the static template expansion (section 4 of the spec). The
`expand_from_findings` hook is the extension point for Phase 2+, once the
extraction stage exists and can feed discovered entities (e.g. an advisor
name, a specific filing number) back into new targeted queries.
"""

from __future__ import annotations

from .models import ResearchQuery

# Angle -> template. "{subject}" is substituted with the raw user input.
_TEMPLATES: dict[str, list[str]] = {
    "general": [
        "{subject}",
        "{subject} deal",
        "{subject} transaction",
        "{subject} announcement",
    ],
    "financial": [
        "{subject} value",
        "{subject} deal value",
        "{subject} price",
        "{subject} enterprise value",
    ],
    "advisors": [
        "{subject} advisors",
        "{subject} financial advisor",
        "{subject} legal advisor",
    ],
    "regulatory": [
        "{subject} regulatory approval",
        "{subject} antitrust",
        "{subject} merger agreement",
        "{subject} SEC filing",
    ],
    "publishers": [
        "{subject} Reuters",
        "{subject} Bloomberg",
        "{subject} Financial Times",
        "{subject} press release",
    ],
    "status": [
        "{subject} closing",
        "{subject} transaction structure",
        "{subject} completed",
    ],
}


def generate_queries(subject: str, iteration: int = 0) -> list[ResearchQuery]:
    """Build the query set for `subject`.

    `iteration` is stamped onto each query so later stages (and logs) can
    tell an initial-pass query apart from one generated by a follow-up
    research loop.
    """
    subject = subject.strip()
    queries: list[ResearchQuery] = []
    seen: set[str] = set()

    for category, templates in _TEMPLATES.items():
        for template in templates:
            text = template.format(subject=subject)
            key = text.lower()
            if key in seen:
                continue
            seen.add(key)
            queries.append(ResearchQuery(text=text, category=category, iteration=iteration))

    return queries


def expand_from_findings(
    subject: str, missing_fields: list[str], known_entities: dict[str, str], iteration: int
) -> list[ResearchQuery]:
    """Generate targeted follow-up queries for fields that are still missing.

    Placeholder for Phase 2 (research loop / iterative search, spec
    section 18). `known_entities` might eventually contain things like
    {"acquirer_financial_advisor": "Goldman Sachs"} discovered during
    extraction, which we can fold into new queries. For now this produces
    simple "<subject> <missing field words>" queries so the research loop
    has something real to call once extraction exists.
    """
    queries: list[ResearchQuery] = []
    seen: set[str] = set()
    for field_name in missing_fields:
        text = f"{subject} {field_name.replace('_', ' ')}"
        key = text.lower()
        if key in seen:
            continue
        seen.add(key)
        queries.append(ResearchQuery(text=text, category="follow_up", iteration=iteration))
    return queries
